name: Build and Test

on:
  pull_request:
    types: [converted_to_draft, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        submodule:
          - ":examples:examples-crud:examples-crud-library"
          - ":examples:examples-search:examples-search-library"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: ./gradlew ${{ matrix.submodule }}:build

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        submodule:
          - ":examples:examples-crud:examples-crud-library"
          - ":examples:examples-search:examples-search-library"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Tests
        run: ./gradlew ${{ matrix.submodule }}:test
