name: Build, Test, and Publish package to GitHub Packages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'Bump version to') }}
    steps:
      - name: Publish package
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publish -PcommitSHA=${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_PACKAGE_TOKEN }}
