name: Publish package to GitHub Packages
on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Identity if Last Commit is Version Bump
        id: check_commit
        run: |
          latest_commit_message=$(git log -1 --pretty=format:"%s")
          if [[ $latest_commit_message == "Bump version to"* ]]; then
            echo "::set-output name=match::true"
          else
            echo "::set-output name=match::false"
          fi

      - name: Publish package
        if: steps.check_commit.outputs.match == 'true'
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publish -PcommitSHA=${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_PACKAGE_TOKEN }}
